### ISSUE TITLE
RHEL 7 os.release.full values are incorrect

### ISSUE THREAD

**Issue by seanmil** [voxpupuli/facterdb#150]
The os.release.full value (seen here https://github.com/camptocamp/facterdb/blob/master/facts/3.14/redhat-7-x86_64.facts#L336) is incorrect for RHEL systems. CentOS systems use that style full version number, but RHEL would be (in this example) just `7.6`, not `7.6.1810`. This seems incorrect in facterdb for a number of versions of facter.

**Comment by anders-larsson** [comment]
#257  fixes this issue, at least if facter 4.2 is used where the files has been updated to use correct values.
