### ISSUE TITLE
Include CentOS 8 stream facts

### ISSUE THREAD

**Issue by ekohl** [voxpupuli/facterdb#164]
I'm looking at supporting CentOS 8 Stream but unsure how to identify this. The problem is that it also identifies as CentOS. The biggest difference is that it doesn't have a minor version:
```json
{
  "os": {
    "architecture": "x86_64",
    "family": "RedHat",
    "hardware": "x86_64",
    "name": "CentOS",
    "release": {
      "full": "8",
      "major": "8"
    },
    "selinux": {
      "enabled": false
    }
  }
}
```

There are examples (https://github.com/puppetlabs/puppetlabs-postgresql/pull/1222) which do regex matching and expect a minor version so I think it important that this can be tested.

**Comment by tobias-urdin** [comment]
From facter 4.0.52 this is populated without having lsb_release, see https://github.com/puppetlabs/facter/pull/2280

**Comment by tobias-urdin** [comment]
I agree with you, was mainly for posterity since this thread comes up high in Google search result to help others out. Making sure we have stream facts, using a later version of facter and bumping version abit higher seems like a preferred way to me.

**Comment by traylenator** [comment]
+1 I agree https://github.com/voxpupuli/facterdb/blob/master/facts/4.2/centos-8-x86_64.facts

should become a stream node.

**Comment by ekohl** [comment]
I updated https://github.com/voxpupuli/facterdb/pull/187. I'd be happy if we could merge that and then change the CentOS 8 box as well.

**Comment by ekohl** [comment]
By now CentOS Linux is EOL and I think we default to stream.
