### ISSUE TITLE
Add AlmaLinux

### ISSUE THREAD

**Issue by maccelf** [voxpupuli/facterdb#173]
Add AlmaLinux support

**Comment by ghoneycutt** [comment]
Hi @maccelf You can submit facts from that OS. 

https://github.com/voxpupuli/facterdb#add-new-operating-system-support

**Comment by alexjfisher** [comment]
@maccelf a PR would be great, but meanwhile I agree that we need to add facts for the new RedHat clones. Do you think it’s just a case of copying the RedHat facts with a couple of modifications or are there more substantial differences?

**Comment by maccelf** [comment]
Hi @alexjfisher, yes i think copying the RedHat facts with a couple of modifications would be enough. But i am added `almalinux/8` in Vagrantfile. And when i run `facter operatingsystem` they returned me `RedHat` because of what the `get_facts.sh` script saves facts in `redhat-8-x86_64.facts` rather than in `almalinux-8-x86_64.facts`,  but in my local machine `facter operatingsystem` returned `AlmaLinux`. Maybe you know where fackter get that value ?

**Comment by ekohl** [comment]
Perhaps you run it with a too old version of Facter that doesn't recognize AlmaLinux?

**Comment by maccelf** [comment]
I am using Facter 3.14

**Comment by ekohl** [comment]
Which exact version? It was only 3.14.17 or 3.14.18 that added support.

**Comment by maccelf** [comment]
Oh, thank you. My exact version Facter on Vagrant VM is 3.14.1 . Then maybe you know why `get_facts.sh` script install Facter 3.14.1 instead 3.14.18 ?

**Comment by ekohl** [comment]
> Oh, thank you. My exact version Facter on Vagrant VM is 3.14.1 . Then maybe you know why `get_facts.sh` script install Facter 3.14.1 instead 3.14.18 ?

Given the PR you've submitted, have you figured it out?

**Comment by maccelf** [comment]
> > Oh, thank you. My exact version Facter on Vagrant VM is 3.14.1 . Then maybe you know why `get_facts.sh` script install Facter 3.14.1 instead 3.14.18 ?
> 
> Given the PR you've submitted, have you figured it out?

Yea, thank you
