### ISSUE TITLE
Several OS files under version 4.2 are missing the mountpoints fact

### ISSUE THREAD

**Issue by michael-riddle** [voxpupuli/facterdb#200]
Hi Folks,

Our spec tests for our internal projects leverage the mountpoints fact and we noticed recently (within the last month) that the spec tests were failing due to mountpoints not actually being set. Looking at the following files in the 4.2 directory, we found many of them were missing that fact. Here's the list:

```
ubuntu-20.04-x86_64.facts
ubuntu-18.04-x86_64.facts
redhat-8-x86_64.facts
freebsd-13-x86_64.facts
freebsd-12-x86_64.facts
freebsd-11-x86_64.facts
fedora-34-x86_64.facts
fedora-33-x86_64.facts
debian-9-x86_64.facts
debian-11-x86_64.facts
centos-9-x86_64.facts
```

**Comment by bastelfreak** [comment]
I am not sure which part creates that fact
* maybe facter was installed but puppet wasnt
* maybe a regression in facter 4.2

do you have facter 4.2 machines where this fact is present?

**Comment by michael-riddle** [comment]
I do not currently, this popped up during spec tests, we specifically saw the issue in rhel 8 and that caused us to poke around in the other facterdb facts to see if it was actually missing from the fact files or not, that's where the list above came from.

I could fairly easily spin up a rhel 8 box, but the other OS's in the list might be a bit more difficult since we don't currently have an automated process to spin those up.

**Comment by bastelfreak** [comment]
every factset is a good step forward, so even a PR for RHEL8 is helpful :) This repository contains also a Vagrant file for most of the operating systems.

**Comment by michael-riddle** [comment]
I created a PR to cover as many of these OS's as I could using the Vagrantfile within facts. There are a few outstanding ones that I couldn't figure out how to get the facts for using the tools provided in the repo as it exists now, but those should be a good start.

**Comment by hbrown-uiowa** [comment]
https://github.com/voxpupuli/facterdb/pull/206 should fix the issue going forward.
