### ISSUE TITLE
service_provider centos 7

### ISSUE THREAD

**Issue by cdenneen** [voxpupuli/facterdb#211]
facter 4.0 had it but 4.1/4.2 do not:

```
❯ grep service_provider ~/.pdk/cache/ruby/2.7.0/gems/facterdb-1.11.0/facts/4.2/centos-7-x86_64.facts
❯ grep service_provider ~/.pdk/cache/ruby/2.7.0/gems/facterdb-1.11.0/facts/4.*/centos-7-x86_64.facts
/Users/cdenneen/.pdk/cache/ruby/2.7.0/gems/facterdb-1.11.0/facts/4.0/centos-7-x86_64.facts:  "service_provider": "systemd",
```

Is this being removed or is there a reason this isn't consistent?

**Comment by bastelfreak** [comment]
I guess the facter 4 factset wasnt created in a clean environment. service_provider is a fact from stdlib, not facter core. facterdb usually only has core facts.

**Comment by ekohl** [comment]
With voxpupuli-test there's code to add the stdlib facts. In https://github.com/voxpupuli/voxpupuli-test/blob/master/lib/voxpupuli/test/facts.rb the `add_mocked_facts!` should add the facts dynamically if stdlib is present in your metadata.

**Comment by ekohl** [comment]
I believe that with #213 this can be considered resolved.
