### ISSUE TITLE
Factsets for FreeBSD 13 have a blank hostname

### ISSUE THREAD

**Issue by msalway** [voxpupuli/facterdb#215]
It looks like when the factsets were regenerated under #210 there have been some unintentional changes to hostname related facts for the FreeBSD 13 factsets that were regenerated.

hostname is now empty string
fqdn has been removed entirely
domain has become "divms.uiowa.edu"

This has happened to both the legacy top-level facts and those nested within the networking tree.

As a result spec tests which expect the host to be named "foo.example.com" or even just a valid domain name are now failing.

**Comment by bastelfreak** [comment]
Hi, thanks for raising the issue. Are you ablento provide a PR with fixed factsets?

**Comment by alexjfisher** [comment]
Even manually fixing up the broken sets (instead of trying to regenerate everything) would be good.
